version: '3.1'
services:
  # TODO: Add example for multiple nodes
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "10.142.0.2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181